module Dimension
  WINDOW_WIDTH =  1280
  WINDOW_HEIGHT = 720
  BOARD_SIDE_SPACE = WINDOW_WIDTH / 10
  BOARD_TOP_SPACE = WINDOW_HEIGHT / 10
  BOARD_WIDTH = WINDOW_WIDTH - 2 * BOARD_SIDE_SPACE
  BOARD_HEIGHT = WINDOW_HEIGHT - 2 * BOARD_TOP_SPACE
  BOARD_NB_COL = 8
end
